# goal is near 'undock' pose with an orientation pointing to standing humans
header:
  seq: 0,
  stamp: now
  frame_id: 'map'
pose:
  position:
    x: -1.0266430378
    y: 0.141307115555
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.129217636827
    w: 0.991616257598
