# hard scenario (starts along the wall)
# <arg name="pose_sim" default="-x 0.2 -y -1.63 -z -0.003 -R 0.0 -P 0.0 -Y -1.5708"/>
{
  initial_cov_aa: 0.02,
  initial_cov_xx: 0.01,
  initial_cov_yy: 0.01,
  initial_pose_a: -1.748,
  initial_pose_x: 0.887,
  initial_pose_y: 2.205
}
