# <arg name="pose_sim" default="-x -1.85 -y -4.00 -z -0.003 -R 0.0 -P 0.0 -Y 0.0"/>
{
  initial_cov_aa: 0.02,
  initial_cov_xx: 0.01,
  initial_cov_yy: 0.01,
  initial_pose_a: -0.162,
  initial_pose_x: -1.650,
  initial_pose_y: 0.185
}
