# pose of the robot while docked and charging;
# valid for a docking station located as in "follow the line board", a.k.a. "v3" world version
{
  initial_cov_aa: 0.02,
  initial_cov_xx: 0.01,
  initial_cov_yy: 0.01,
  initial_pose_a: +3.033,
  initial_pose_x: +2.873,
  initial_pose_y: +6.061
}
