# shorter
# <arg name="pose_sim" default="-x 1.73 -y -1.25 -z -0.003 -R 0.0 -P 0.0 -Y -2.18"/>
{
  initial_cov_aa: 0.02,
  initial_cov_xx: 0.01,
  initial_cov_yy: 0.01,
  initial_pose_a: -2.18,
  initial_pose_x: 1.73,
  initial_pose_y: -1.25
}
